{% set name = "azure-cli-core" %}
{% set version = "2.67.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a19f345edc4f1a7bad0a1cfc3e6a7393adcc916ab489b48341792d7b78aa4cc2

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - argcomplete >=3.3.0
    - azure-cli-telemetry >=1.1.0
    - azure-mgmt-core >=1.2.0,<2
    - cryptography
    - distro
    - humanfriendly >=10.0
    - jmespath
    - knack >=0.11.0
    # - microsoft-security-utilities-secret-masker >=1.0.0b2
    - msal_extensions >=1.2.0
    - msal >=1.31.0
    # - pymsalruntime >=0.17.0
    - msrestazure ~=0.6.4
    - packaging >=20.9
    - pkginfo >=1.5.0.1
    - pyjwt >=2.1.0
    - pyopenssl >=17.1.0
    - requests >=2.20.0
    - pysocks >=1.6.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure
    - azure.cli
    - azure.cli.core
    - azure.cli.core.commands
    - azure.cli.core.extension
    - azure.cli.core.profiles

about:
  home: https://github.com/Azure/azure-cli
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Azure Command-Line Tools Core Module

  doc_url: https://docs.microsoft.com/en-us/cli/azure
  dev_url: https://github.com/Azure/azure-cli

extra:
  recipe-maintainers:
    - dhirschfeld
    - andreyz4k
