{% set name = "azure-cli-core" %}
{% set version = "2.48.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 28c80e5a449d8e73d16dbe96196d6277d564a8225842c5e7f84fcc53ee4f4f39

build:
  skip: true  # [win or py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - argcomplete ~=2.0
    - azure-cli-telemetry =1.0.8
    - azure-mgmt-core >=1.2.0,<2
    - cryptography
    - distro  # [linux]
    - humanfriendly ~=10.0
    - jmespath
    - knack ~=0.10.1
    - msal-extensions ~=1.0.0
    - msal =1.20.0
    - msrestazure ~=0.6.4
    - packaging >=20.9
    - paramiko >=2.0.8,<4.0.0
    - pkginfo >=1.6
    - psutil ~=5.9
    - pyjwt >=2.1.0
    - pymsalruntime >=0.13.2,<0.14  # [win]
    - pysocks >=1.6.0
    - pyopenssl >=17.1.0
    - requests >=0.13.2,<0.14

test:
  imports:
    - azure
    - azure.cli
    - azure.cli.core
    - azure.cli.core.commands
    - azure.cli.core.extension
    - azure.cli.core.profiles

about:
  home: https://github.com/Azure/azure-cli
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Azure Command-Line Tools Core Module

  doc_url: https://docs.microsoft.com/en-us/cli/azure
  dev_url: https://github.com/Azure/azure-cli

extra:
  recipe-maintainers:
    - dhirschfeld
    - andreyz4k
