{% set name = "azure-cli-core" %}
{% set version = "2.70.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a511439f6dd32092eb4bc1d99debdacff87981325b7c3afb2e0534ce6ca071bd

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - microsoft-security-utilities-secret-masker >=1.0.0b2,<1.1.dev0
    - py-deviceid
    - python >={{ python_min }}
    - argcomplete >=3.5.2,<3.6.dev0
    - azure-cli-telemetry ==1.1.0.*
    - azure-mgmt-core >=1.2.0,<2
    - cryptography
    - distro
    - humanfriendly >=10.0,<11.dev0
    - jmespath
    - knack >=0.11.0,<0.12.dev0
    # - microsoft-security-utilities-secret-masker ~=1.0.0b2
    - msal_extensions ==1.2.0
    - msal ==1.31.2b1
    - msrestazure >=0.6.4,<0.7.dev0
    - packaging >=20.9
    - pkginfo >=1.5.0.1
    - psutil >=5.9
    - pyjwt >=2.1.0
    - pyopenssl >=17.1.0
    - requests
    - pysocks >=1.6.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure
    - azure.cli
    - azure.cli.core
    - azure.cli.core.commands
    - azure.cli.core.extension
    - azure.cli.core.profiles

about:
  home: https://github.com/Azure/azure-cli
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Azure Command-Line Tools Core Module

  doc_url: https://docs.microsoft.com/en-us/cli/azure
  dev_url: https://github.com/Azure/azure-cli

extra:
  recipe-maintainers:
    - dhirschfeld
    - andreyz4k
