{% set name = "azure-cli-core" %}
{% set version = "2.0.61" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15184b916e9ebaab4a630716d980384992f6d6084cf2eff23c704ecaf421adf6

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - adal >=1.2.0
    - antlr-python-runtime
    - argcomplete >=1.8.0
    - azure-cli-telemetry
    - azure-mgmt-resource ==2.1.0
    - colorama >=0.3.9
    - humanfriendly >=4.7
    - jmespath
    - knack ==0.5.1
    - msrest >=0.4.4
    - msrestazure >=0.4.25
    - paramiko >=2.0.8
    - pip
    - pygments
    - pyjwt
    - pyopenssl >=17.1.0
    - pyyaml
    - requests >=2.20.0
    - six
    - tabulate >=0.7.7,<=0.8.2
    - wheel

test:
  imports:
    - azure
    - azure.cli
    - azure.cli.core
    - azure.cli.core.commands
    - azure.cli.core.extension
    - azure.cli.core.profiles

about:
  home: https://github.com/Azure/azure-cli
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Azure Command-Line Tools Core Module

  doc_url: https://docs.microsoft.com/en-us/cli/azure
  dev_url: https://github.com/Azure/azure-cli

extra:
  recipe-maintainers:
    - andreyz4k
