schema_version: 1

context:
  name: azure-cli-core
  version: "2.74.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 13acb127f8b9c4733e4742d0f77cc5687ebdad651a4ea3f90afce8dbae98dfea

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - argcomplete >=3.5.2,<3.5.3
    - azure-cli-telemetry >=1.1.0
    - azure-mgmt-core >=1.2.0,<2
    - cryptography
    - distro
    - humanfriendly >=10.0
    - jmespath
    - knack >=0.11.0,<0.11.1
    - microsoft-security-utilities-secret-masker >=1.0.0b2,<1.1.0
    - msal ==1.32.3
    - msal_extensions ==1.2.0
    - msrestazure ~=0.6.4
    - packaging >=20.9
    - pkginfo >=1.5.0.1
    - psutil >=5.9
    - py-deviceid
    - pyjwt >=2.1.0
    - pyopenssl >=17.1.0
    - pysocks >=1.6.0
    - requests >=2.20.0

tests:
  - python:
      imports:
        - azure
        - azure.cli
        - azure.cli.core
        - azure.cli.core.commands
        - azure.cli.core.extension
        - azure.cli.core.profiles
      python_version: ${{ python_min }}.*
about:
  license: MIT
  license_file: LICENSE
  summary: Microsoft Azure Command-Line Tools Core Module
  homepage: https://github.com/Azure/azure-cli
  repository: https://github.com/Azure/azure-cli
  documentation: https://docs.microsoft.com/en-us/cli/azure

extra:
  recipe-maintainers:
    - dhirschfeld
    - andreyz4k
    - janjagusch
